# Generated by Django 5.1.11 on 2025-07-19 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                ("likes", models.IntegerField(default=0)),
                ("added_date", models.CharField(max_length=50)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "ordering": ["-added_date"],
            },
        ),
        migrations.DeleteModel(
            name="TodoItem",
        ),
    ]
